'use strict';

module.exports =
  angular.module('SimplySocial', [
    'ui.router',
    'ngSanitize',
    // html templates in $templateCache generated by Gulp:
    require('../../../tmp/templates').name,
    // useful directives, filters, services shared across the app
    require('../common').name,
    // app module:
    require('./navbar').name,
    require('./home').name,
    //load extra app modules here, e.g.:
    //require('./frontend').name,
    //require('./admin').name
  ]);
